// JavaScript Document

function writeNavBar() {
	
document.write("<p><a href='../../../index.htm'>Home</a> &#8226; <a href='../intro/intro_page0.htm'>Introduction</a> &#8226; <a href='../ortho/ortho_page0.htm'>Orthographic Projection</a> &#8226; <a href='../pic/pic_page0.htm'>Pictorials</a> &#8226; <a href='dim_page0.htm'>Dimensioning</a> &#8226; <a href='../sec/sec_page0.htm'>Sectioning</a> &#8226; <a href='../adv/adv_page0.htm'>Advanced Drawing Techniques</a> &#8226; <a href='../tol/tol_page0.htm'>Tolerancing</a> &#8226; <a href='../fast/fast_page0.htm'>Threads &amp; Fasteners</a> &#8226; <a href='../assem/assem_page0.htm'>Assembly</a> </p>");
	
}

function writeLeftBar() {
	
	document.write("<p> 1) <a href='dim_page1.htm'>Detailed Drawings</a><br /> 2) <a href='dim_page2.htm'>Learning to Dimension</a><br /> 3) <a href='dim_page3.htm'>Dimension Appearance</a><br /> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page3_ex1.htm'>Dim. appearance</a><br/> 4) <a href='dim_page4.htm'>Feature Dimensions</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page4_ex1.htm'>Feature dim. 1</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page4_ex2.htm'>Circular and rectangular views</a><br /> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page4_ex3.htm'>Feature dim. 2</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page4_ex4.htm'>Feature dim. 3</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page4_ex5.htm'>Feature dim. 4</a><br/> 5) <a href='dim_page5.htm'>Dimension Rules</a><br /> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex1.htm'>Spacing and readability 1</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex2.htm'>Spacing and readability 2</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex3.htm'>Dim. placement</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex4.htm'>Missing dim.</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex5.htm'>Duplicate dim.</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex6.htm'>Reference dimensions</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex7.htm'>Dimensioning</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex9.htm'>Rounding off</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex8.htm'>Dim. accuracy</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226;  Exercise: <a href='dim_page5_ex10.htm'>Advanced dim.</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex11.htm'>Dimension choice</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Video: <a href='dim_page5_v1.htm'>Beginning</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Video: <a href='dim_page5_v2.htm'>Intermediate</a><br/>  &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Video: <a href='dim_page5_v3.htm'>Advanced 1</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Video: <a href='dim_page5_v4.htm'>Advanced 2</a><br /> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page5_ex12.htm'>Tolerances</a><br/> 6) <a href='dim_page6.htm'>Applying what we have learned</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page6_ex1.htm'>Dimensioning 1</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page6_ex2.htm'>Dimensioning 2</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page6_ex3.htm'>Dimensioning 3</a><br/> &nbsp;&nbsp;&nbsp;&nbsp;&#8226; Exercise: <a href='dim_page6_ex4.htm'>Dimensioning 4</a><br/> 7) <a href='dim_page7.htm'>Supplemental Problems</a><br/>  </p>");
	  
}